# Site settings
name: HYX bioinformatics
email: hyx314@foxmail.com
author: Yuxuan Huang
url: https://xanadu314.github.io/bio/
resume_site: https://xanadu314.github.io/bio/

baseurl: "/LessOrMore"
description: stay hungry stay foolish
meta_description: Bioinformatics collection
motto: It's our wits that make us men.
banner: 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: xanadu314

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

